### PR TITLE
Chore/log google font error

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@rodrigopavezi @stulees Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep Do you think we should also log when all fonts weren't loaded via `inactive` event?

**Comment by donnapep** [comment]
@stulees I don't think it's strictly necessary since we're already logging the each of the individual fonts that fail to load.

**Comment by stulees** [comment]
@donnapep What if all fonts (600+) fail? Will we result in 600+ log calls?

**Comment by donnapep** [comment]
@stulees I thought Text Widget only loads the fonts that are actually being used? So I think that will only happen if someone uses all 600.

**Comment by stulees** [comment]
@donnapep You're right, my mistake, I was still thinking in context of Settings. :+1:

**Pull request merged**
