### PR TITLE
Feature/load more fonts

### PR DESCRIPTION
**Pull request by donnapep**
Had to move `ng-if` out of `textarea` to resolve this bug - https://github.com/angular/angular.js/issues/13174.

Presentation - http://goo.gl/7Lx2jh

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Comment by stulees** [comment]
@donnapep :+1: but I think we're going to need a loading spinner when load more fonts is triggered. From a user experience there's a significant delay from selecting "Load more fonts" to the refresh of the editor.

**Comment by donnapep** [comment]
@stulees I agree. It's annoying that we have to refresh the editor. We also need to get rid of the text area showing on a refresh and when first loading. That's especially ugly.

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review latest commits. Thx.

**Comment by stulees** [comment]
@donnapep Looks good :+1:

**Comment by rodrigopavezi** [comment]
@donnapep looks good :+1: cheers

**Pull request merged**
