### PR TITLE
Handling spaces and single quotes in custom font file name [stage-2]

### PR DESCRIPTION
**Pull request by stulees**
- Decoding custom url value to set family name with actual spaces
- Escaping single quotes in custom font url
- Updating custom font test coverage to account for a file with spaces and single quotes

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, this is a fix for issue #59 , thanks.

**Comment by stulees** [comment]
@donnapep @rodrigopavezi It appears that the escaping of single quotes and saving these values to additionalParams are causing Viewer a problem in rendering. 

I keep saving a presentation here - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=5d3daac6-e6d0-4195-a7e9-c16b24b667da?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

The settings work and save and restore correctly while I'm in the presentation. When I leave the presentation and come back to it, it's blank.

When I test locally using widget-preview, everything works fine on both the settings and widget side. Any ideas as to how to get around this?

**Comment by stulees** [comment]
@donnapep @rodrigopavezi I've corrected the issue I was previously having, please review, thanks. 

Presentation - http://rva.risevision.com/#/PRESENTATION_MANAGE/id=84aac5c9-f50a-425a-a858-307666e0cbc4?cid=30007b45-3df0-4c7b-9f7f-7d8ce6443013

**Comment by rodrigopavezi** [comment]
@stulees looks good. :+1:  cheers

**Pull request merged**
